language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
script:
  - env PYTHONPATH=`pwd` coverage run --source=feedback_form runtests.py
after_success:
  coveralls
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.4.2
    - python: "3.3"
      env: DJANGO_VERSION=1.4.2
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.8
